### PR TITLE
docs: fix jupyter sphinx config

### PR DESCRIPTION
**Pull request by lepture**
This will fix the conflict between jupyter-sphinx extension with mermaid and docsearch.

https://shibuya.lepture.com/extensions/mermaid/#mermaid-not-working

### CODE REVIEW

**Comment by Tobi-De** [comment]
> This will fix the conflict between jupyter-sphinx extension with mermaid and docsearch.
> 
> https://shibuya.lepture.com/extensions/mermaid/#mermaid-not-working

So there was one, I didn't know that, thank you.

**Comment by Tobi-De** [comment]
@lepture any idea how I can get rid of this 

image

**Comment by Tobi-De** [comment]
@all-contributors add @lepture for bug

**Comment by lepture** [comment]
@Tobi-De You can create an empty file at `docs/_templates/components/nav-versions.html`.

**Comment by Tobi-De** [comment]
> @Tobi-De You can create an empty file at `docs/_templates/components/nav-versions.html`.

Ok thanks

**Pull request merged**
